FOREST:
  bg_file: bg_forest.png
  music_file: bgMusic.mp3
  tile_set_file: tile_set.png

  tile_rects:
    top_rects:
        - { x: 32, y: 0, w: 16, h: 16 }
        - { x: 48, y: 0, w: 16, h: 16 }
        - { x: 64, y: 0, w: 16, h: 16 }
    center_rects:
        - { x: 32, y: 32, w: 16, h: 16 }
        - { x: 48, y: 32, w: 16, h: 16 }
        - { x: 64, y: 32, w: 16, h: 16 }
    bottom_rects:
        - { x: 32, y: 48, w: 16, h: 16 }
        - { x: 48, y: 48, w: 16, h: 16 }
        - { x: 64, y: 48, w: 16, h: 16 }

DUNGEON:
  bg_file: bg_city.png
  music_file: bgMusic.mp3
  tile_set_file: dungeon_tile_set.png

  tile_rects:
    top_rects:
        - { x: 16, y: 16, w: 16, h: 16 }
        - { x: 32, y: 16, w: 16, h: 16 }
        - { x: 48, y: 16, w: 16, h: 16 }
    center_rects:
        - { x: 16, y: 32, w: 16, h: 16 }
        - { x: 32, y: 32, w: 16, h: 16 }
        - { x: 48, y: 32, w: 16, h: 16 }
    bottom_rects:
        - { x: 16, y: 48, w: 16, h: 16 }
        - { x: 32, y: 48, w: 16, h: 16 }
        - { x: 48, y: 48, w: 16, h: 16 }

LINE:
  bg_file: bg_black.png
  music_file: bgMusic.mp3
  tile_set_file: line_tile_set.png

  tile_rects:
    top_rects:
        - { x: 240, y: 208, w: 16, h: 16 }
        - { x: 256, y: 208, w: 16, h: 16 }
        - { x: 272, y: 208, w: 16, h: 16 }
    center_rects:
        - { x: 240, y: 224, w: 16, h: 16 }
        - { x: 256, y: 224, w: 16, h: 16 }
        - { x: 272, y: 224, w: 16, h: 16 }
    bottom_rects:
        - { x: 240, y: 240, w: 16, h: 16 }
        - { x: 256, y: 240, w: 16, h: 16 }
        - { x: 272, y: 240, w: 16, h: 16 }