#ifndef PHYSICS_CONSTANTS_H
#define PHYSICS_CONSTANTS_H


#define COEFFICIENT_FRICTION_FLOOR 200
#define COOLDOWN_FLAPPING 0.10

// duck
#define INTENSITY_JUMPING 60
#define INTENSITY_FLAPPING 20

// weapons
#define DISPERSION_RATE_AK47 0.3
#define RECOIL_AK47 12
#define RECOIL_LASER 13
#define RECOIL_MAGNUM 12
#define DAMAGE_MULTIPLES_PROJECTILES(x) ((x) / 9)
#endif
