#ifndef PHYSICS_CONSTANTS_H
#define PHYSICS_CONSTANTS_H


#define COEFFICIENT_FRICTION_FLOOR 200
#define COOLDOWN_FLAPPING 0.10
#define HALF_SPIN 180
#define FULL_SPIN 360

// duck
#define INTENSITY_JUMPING 60
#define INTENSITY_FLAPPING 20

// weapons
#define DISPERSION_RATE_AK47 0.3
#define RECOIL_AK47 14
#define RECOIL_LASER 15
#define RECOIL_MAGNUM 13
#define DAMAGE_MULTIPLES_PROJECTILES(x) ((x) / 9)

// explotion
#define INTENSITY_EXPLOTION 30
#define SCOPE_EXPLOTION 30
#define DAMAGE_EXPLOTION 6

#define INTENSITY_SLIDE_DUCK 50
#define INTENSITY_SLIDE_BANANA 14

#endif
