shooting_inclination:
  basic: 0
  laser_rifle: -45

projectiles_per_shot:
  basic: 1
  granade: 10
  box: 6

cooldown:
  none: 0
  basic: 0.6
  short: 1
  medium: 2.5
  long: 7.5
  to_explote_granade: 4

damage:
  minimun: 10
  short: 12
  medium: 17
  long: 20
  
dispersion:
  no_dispersion: 0
  long: 0.4
  short: 0.15
  super: 0.45
  hiper: 9

banana:
  scope: 13
  ammo: 1

granade:
  scope: 25
  ammo: 1

pew_pew_laser:
  scope: 44 # 35 a 38
  ammo: 12

laser_rifle:
  scope: 38
  ammo: 10

ak47:
  scope: 17
  ammo: 30

dueling_pistol:
  scope: 9
  ammo: 1

cowboy_pistol:
  scope: 25
  ammo: 6

magnum:
  scope: 25
  ammo: 6

shotgun:
  scope: 10 # 7 a 9
  ammo: 2

sniper:
  scope: 80
  ammo: 3

