shooting_inclination:
  basic: 0
  laser_rifle: -45

projectiles_per_shot:
  basic: 1

cooldown:
  none: 0
  basic: 0.3
  short: 1
  medium: 2.5
  long: 7.5
  to_explote_granada: 4

damage:
  minimun: 10
  short: 12
  medium: 17
  long: 20
  
dispersion:
  no_dispersion: 0
  long: 0.4
  short: 0.15
banana:
  scope: 10
  ammo: 1

granada:
  scope: 20
  ammo: 1

laser_rifle:
  scope: 30
  ammo: 100

cowboy_pistol:
  scope: 20
  ammo: 6


