theme: DUNGEON
full_map_size:
  x: 1600
  y: 1000

collectable_spawn_points:
  - x: -25
    y: 36
  - x: 25
    y: 36
  - x: 22
    y: 15
  - x: -22
    y: 15
  - x: 20
    y: -40
  - x: -20
    y: -40

players_spawn_points:
  - x: 20
    y: 14
  - x: -20
    y: 14
  - x: 40
    y: -9
  - x: -40
    y: -9

box_spawn_points:
  - x: -20
    y: 35
  - x: 20
    y: 35
  
platforms:
  - platform_1
  - platform_2
  - platform_3
  - platform_4
  - platform_5
  - platform_6
  - platform_7
  - platform_8
  - platform_9
  - platform_10
  - platform_11
  - platform_12
  - platform_13
  - platform_14
  - platform_15
  - platform_16
  - platform_17
  - platform_18
  - platform_19
  - platform_20
  - platform_21

platform_1:
  x: 0
  y: -25
  w: 20
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_2:
  x: 25
  y: -45
  w: 30
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_3:
  x: -25
  y: -45
  w: 30
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_4:
  x: 50
  y: -35
  w: 30
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_5:
  x: -50
  y: -35
  w: 30
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_6:
  x: -65
  y: -25
  w: 10
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_7:
  x: 65
  y: -25
  w: 10
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_8:
  x: 60
  y: -10
  w: 10
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_9:
  x: -60
  y: -10
  w: 10
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_10:
  x: 75
  y: -15
  w: 10
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_11:
  x: -75
  y: -15
  w: 10
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_12:
  x: 40
  y: -15
  w: 20
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_13:
  x: -40
  y: -15
  w: 20
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_14:
  x: 20
  y: -10
  w: 15
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_15:
  x: -15
  y: -10
  w: 15
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_16:
  x: 2.5
  y: 0
  w: 15
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT 

platform_17:
  x: 22.5
  y: 10
  w: 20
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_18:
  x: -20
  y: 10
  w: 20
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_19:
  x: 2.5
  y: 20
  w: 15
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT 

platform_20:
  x: 20
  y: 30
  w: 20
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT

platform_21:
  x: -20
  y: 30
  w: 20
  h: 8
  edges:
  - TOP
  - BOTTOM
  - LEFT
  - RIGHT