theme: DUNGEON
full_map_size:
  x: 100
  y: 160
collectable_spawn_points:
  - x: -18
    y: 10
  - x: 40
    y: -10

players_spawn_points:
  - x: -18 
    y: 12
  - x: 40
    y: -8
  - x: -9
    y: 10
  - x: -25
    y: 10
  - x: 0
    y: 10
box_spawn_points:
  - x: 48
    y: 5
  - x: -30
    y: 9
  
platforms:
  - platform_one
  - platform_two
  - platform_three
  - platform_four
  - platform_five
  - platform_six
  - platform_seven
  - platform_eight
platform_one:
  x: 0
  y: -12
  w: 24
  h: 8
  edges: 
  - RIGHT
  - TOP
  - BOTTOM

platform_two:
  x: -32
  y: 0
  w: 40
  h: 16
  edges: 
  - LEFT
  - RIGHT
  - TOP

platform_three:
  x: -32
  y: -12
  w: 40
  h: 8
  edges: 
  - LEFT
  - BOTTOM

platform_four:
  x: 28
  y: -8
  w: 16
  h: 8
  edges: 
  - LEFT
  - RIGHT
  - TOP

platform_five:
  x: 28
  y: -20
  w: 16
  h: 16
  edges: 
  - LEFT
  - BOTTOM

platform_six:
  x: 40
  y: -20
  w:  8
  h: 16
  edges : 
  - TOP
  - BOTTOM

platform_seven:
  x:  48
  y: -20
  w: 8
  h: 16
  edges: 
  - RIGHT
  - BOTTOM

platform_eight:
  x:  48
  y: -4
  w: 8
  h: 16
  edges: 
  - RIGHT
  - LEFT
  - TOP


