name: pre-commit hooks and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    
    - name: Install cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck
          
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files
        
    # Instalar SDL2
    #- name: Install SDL2 
    #  run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

     # Instalar SDL2_image
    #- name: Install SDL2_image
    #  run: sudo apt-get install -y libsdl2-image-dev

    # Instalar SDL2_ttf
    #- name: Install SDL2_ttf
    #  run: sudo apt-get install -y libsdl2-ttf-dev

    #Instalar SDL2_mixer
    #- name: Install SDL2_mixer
    #  run: sudo apt-get install -y libsdl2-mixer-dev
      
    # Instalar herramientas necesarias para la compilación
    #- name: Install dependencies
    #  run: sudo apt-get install -y cmake unzip

    # Actualizar los submódulos (si el proyecto los usa)
    #- name: Update submodules
    #  run: git submodule update --init --recursive
    
    - name: Dar permisos de ejecución
      run: chmod +x ./install_dependencies.sh
    - name: instalar dependencias
      run: ./install_dependencies.sh
      
    # Ejecutar CMake y compilar
    - name: Build project
      run: |
       cd build
       # cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DSDL2PP_WITH_IMAGE=ON -DSDL2PP_WITH_TTF=ON -DSDL2PP_WITH_MIXER=ON
    - name: Build project using make
      run: make
