name: Install Dependencies and Build Project

on:
  push:
    branches:
      - main  # o la rama donde desees probar el script
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa una máquina virtual Ubuntu más reciente
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: sudo apt-get update -y

    - name: Install dependencies
      run: |
        chmod +x install_dependencies.sh  # Asegúrate de que tu script sea ejecutable
        ./install_dependencies.sh         # Ejecuta tu script

    - name: Verify installation of packages
      run: |
        dpkg -s libsdl2-dev libyaml-dev
        # Agrega más verificaciones si es necesario para asegurar que las dependencias estén instaladas correctamente

    - name: Build the project
      run: |
        make clean || true  # Evita fallos si no existe el Makefile
        make                # Construye el proyecto

    - name: Run tests (optional)
      run: |
        # Si tienes pruebas automatizadas, puedes ejecutarlas aquí
        # Ejemplo:
        # ./run_tests.sh
